
services:
  db_neo4j:
    image: neo4j:5
    container_name: ${PROJECT_NAME}_db_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/admin123
      - NEO4J_initial_dbms_default__database=db-graphrag-agent
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*

  # # Ollama Server
  ollama:
    build: 
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ${PROJECT_NAME}_ai_ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: ${AI_OLAMA_CPU}
    environment:
      - OLLAMA_MODELS=sam860/exaone-4.0:1.2b-thinking-Q8_0,bge-m3:567m
      - OLLAMA_NUM_PARALLEL=${AI_OLAMA_CPU}
      - OLLAMA_MAX_LOADED_MODELS=1      


  # FastAPI application
  app_fullstack:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
    container_name: ${PROJECT_NAME}_app_fullstack
    # restart: unless-stopped
    ports:
      - "8000:8000"
      - "3000:3000"
    stdin_open: true
    tty: true
